### ISSUE TITLE
KC_LCAP does not seem to working as expected 

### ISSUE THREAD

**Issue by sfnvm** [profet23/atreus62#10]
Hi there. Just got my keyboard yesterday, everything seem to working fine except when I'm remapping the layouts (adding caps lock key (layer 0), lock caps lock (layer 1)) and keyboard's behaving like [this](https://www.reddit.com/r/olkb/comments/7b9wbk/qmkhelp_programming_a_locking_switch/)

**Current layout**
<img width="644" alt="Screen Shot 2021-02-06 at 10 25 50 PM" src="https://user-images.githubusercontent.com/37434290/107122447-69a47480-68ca-11eb-8793-db2297086bea.png">

**Comment by profet23** [comment]
I'm not entirely sure what you're asking. 

If the switches are working as intended with the standard firmware, and you can't get your desired functionality with a custom qmk firmware layout, this is probably a question for the qmk forums.

**Comment by sfnvm** [comment]
@profet23 Right, thank you for your time.
