### ISSUE TITLE
trouble finding `/dev/tty*` port with a macbook pro (usb-c)

### ISSUE THREAD

**Issue by tatums** [profet23/atreus62#4]
I had some trouble finding the correct tty port.  I'm using a macbook pro which has usb-c ports.  

#### background/context
* I ordered mine prebuild so the micro controller was already programmed.
* Since the macbook has usb-c ports I'm using an [apple usb dongle](https://www.apple.com/shop/product/MJ1K2AM/A/usb-c-digital-av-multiport-adapter)

#### Here's how I found the correct tty port.
* First, flip the keyboard over and use a paperclip to hit keyboards reset button.
* Then, you [have ~8 seconds where the micro controller](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/troubleshooting-and-faq#ts-reset) is viewable using `ls /dev/tty*`.  After 8 seconds it's no longer viewable. In my case it appears as `/dev/tty.usbmodem14411`

BTW, feel free to close this issue.  I'm only sharing because it wasn't immediately obvious to me and I thought others may find this helpful.

**Comment by profet23** [comment]
If you want, you could submit a pull request with documentation updates. For now I'll close this issue.
