### ISSUE TITLE
CAD-files are cut off

### ISSUE THREAD

**Issue by jinithin** [profet23/atreus62#5]
Looking to print out an Atreus62 and when I tried to use the cad files available I saw that they were cut off, only displaying one half.

Is it possible to fix these or make a DXF-file available for all layers?
Thanks!

**Comment by profet23** [comment]
What program are you using?  Try [inkscape](https://inkscape.org)

**Comment by jinithin** [comment]
Oh, that seem to have worked.
Thanks!

Also, when exporting to dxf, what dimensions should be used?
Inches? Millimetre?
Or is it not according to scale?

**Comment by profet23** [comment]
Depends on how your'e exporting? What are you trying to do? Why not just use the svg's? dxf's do not have units.

**Comment by jinithin** [comment]
I'm exporting via Inkscape. I have to do it as the laser-cutting company only takes dxf as a file option.
Did not know that they don't include units.
I'll just import the dxf at the lasercutting-site and resize it there.

What's the dimensions for the atreus? (length, height etc.).
Can't find them in the repo.

Thanks for the patience.

**Comment by profet23** [comment]
Open the svg in inkscape and use the ruler to get the exact dimensions you're looking for.

**Comment by profet23** [comment]
You ok with closing this issue now?

**Comment by jinithin** [comment]
Oh yeah, I see now.
Thanks.

**Comment by profet23** [comment]
Also... if you're looking for a custom case cut... hit me up here:  https://shop.profetkeyboards.com/custom-builds
