### ISSUE TITLE
Any way to add WS2812b support? Multiplex a pin?

### ISSUE THREAD

**Issue by jsmestad** [profet23/atreus62#7]
It appears all pins on the pro micro are used for the key matrix. Have you done any builds or mods to support RGB anywhere (like a WS2812b)? I am new to QMK and wasnt sure if the matrix scanning code could support pin multiplexing without impacting the matrix scanning code. Any ideas or am I out of luck?

**Comment by profet23** [comment]
Yes. RGB can be supported. I recommend using an Elite-C controller instead of a pro-micro for this.

QMK firmware for elite-c and RGB underglow:  https://github.com/profet23/qmk_firmware/tree/atreus62_rgb.

Uses Elite-C Pin B7 and 31 RGB LEDs from a WS2812B strip.
